"""
Read a measurements file generated by eval_limesdr_fpga.py
and plots the PER/SNR curve, plus CFO values.
"""

import sys
from collections import defaultdict

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

if __name__ == "__main__":
    expected_payload = np.arange(100, dtype=np.uint8)
    num_bits = len(expected_payload) * 8

    data = defaultdict(list)
    with open(sys.argv[1]) as f:
        for line in f.read().splitlines():
            if line.startswith("CFO"):
                cfo, sto = line.split(",")
                data["cfo"].append(float(cfo.split("=")[1]))
                data["sto"].append(int(sto.split("=")[1]))
            elif line.startswith("SNR"):
                snr, txp = line.split(",")
                data["snr"].append(float(snr.split("=")[1]))
                data["txp"].append(int(txp.split("=")[1]))
            elif line.startswith("packet"):
                *_, payload = line.split(",", maxsplit=2)
                payload = list(map(int, payload.split("=")[1][1:-1].split(",")))
                ber = (
                    np.unpackbits(
                        expected_payload ^ np.array(payload, dtype=np.uint8)
                    ).sum()
                    / num_bits
                )
                invalid = 1 if ber > 0 else 0
                data["ber"].append(ber)
                data["invalid"].append(invalid)

        df = pd.DataFrame.from_dict(data)

        print(df)
        df.to_csv('measures_df.csv', index=False)

    fig = df.groupby("txp").hist(column="cfo")
    plt.show()
"""
    # Plot BER vs. SNR
    plt.figure()
    plt.plot(df["snr"], df["ber"], 'o-', label="BER")
    plt.xlabel("SNR (dB)")
    plt.ylabel("Bit Error Rate (BER)")
    plt.title("BER vs. SNR")
    plt.legend()
    plt.grid(True)
    plt.savefig('ber_vs_snr.png')
    plt.show()

    # Calculate and plot PER vs. SNR
    df['per'] = df['invalid'].cumsum() / (df.index + 1)
    plt.figure()
    plt.plot(df["snr"], df["per"], 's-', label="PER")
    plt.xlabel("SNR (dB)")
    plt.ylabel("Packet Error Rate (PER)")
    plt.title("PER vs. SNR")
    plt.legend()
    plt.grid(True)
    plt.savefig('per_vs_snr.png')
    plt.show()
"""
